# Generated by Django 3.1.2 on 2020-12-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(db_index=True, help_text='Введите название подразделения', max_length=256, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['dep_name'],
            },
        ),
        migrations.CreateModel(
            name='LetterOfInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('loi_employee', models.CharField(help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='Принимаемый сотрудник')),
                ('loi_position', models.CharField(help_text='Введите должность принимаемого сотрудника', max_length=256, verbose_name='Должность')),
                ('loi_department', models.CharField(help_text='Введите подразделение принимаемого сотрудника', max_length=256, verbose_name='Подразделение')),
                ('loi_dateOfInv', models.DateField(blank=True, db_index=True, help_text='Введите дату начала работы', null=True, verbose_name='Дата начала работы')),
                ('loi_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на прием',
                'verbose_name_plural': 'Заявления на прием',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LetterOfResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lor_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('lor_employee', models.CharField(help_text='Введите ФИО увольняемого сотрудника', max_length=256, verbose_name='Увольняемый сотрудник')),
                ('lor_position', models.CharField(help_text='Введите должность увольняемого сотрудника', max_length=256, verbose_name='Должность')),
                ('lor_departament', models.CharField(help_text='Введите подразделение увольняемого сотрудника', max_length=256, verbose_name='Подразделение')),
                ('lor_dateOfRes', models.DateField(db_index=True, help_text='Введите дату увольнения', verbose_name='Дата увольнения')),
                ('lor_additionalData', models.CharField(blank=True, default='примечание', help_text='Введите примечание', max_length=256, verbose_name='Примечание')),
                ('lor_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnOtherMatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oom_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=5, verbose_name='Номер приказа')),
                ('oom_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('oom_content', models.CharField(help_text='Введите содержание приказа', max_length=256, verbose_name='Содержание')),
                ('oom_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ по другим вопросам',
                'verbose_name_plural': 'Приказы по другим вопросам',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnVacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oov_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=8, verbose_name='Номер приказа')),
                ('oov_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('oov_empList', models.TextField(help_text='Введите сотрудников в приказ', verbose_name='Список сотрудников в приказе')),
                ('oov_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ на отпуск',
                'verbose_name_plural': 'Приказы на отпуск',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutBoundDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, default='Письмо', help_text='Введите вид документа (письмо, справка, и.т.д)', max_length=100, verbose_name='Вид')),
                ('doc_date', models.DateField(db_index=True, help_text='Введите дату документа', verbose_name='Дата документа')),
                ('doc_dest', models.CharField(help_text='Введите адресата', max_length=256, verbose_name='Получатель (адресат)')),
                ('doc_additionalData', models.CharField(default='none', help_text='Введите содержание документа', max_length=256, verbose_name='Содержание документа')),
                ('doc_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Исходящий документ',
                'verbose_name_plural': 'Исходящие документы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=5, verbose_name='Номер приказа')),
                ('op_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('op_emloyer', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО сотрудника')),
                ('op_content', models.TextField(help_text='Введите содержание', verbose_name='Содержание приказа')),
                ('op_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('op_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Приказ по личному составу',
                'verbose_name_plural': 'Приказы по личному составу',
                'ordering': ['op_number'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOfBTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=5, verbose_name='Номер приказа')),
                ('bt_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('bt_place', models.CharField(db_index=True, help_text='Введите место командировки', max_length=256, verbose_name='Место командировки')),
                ('bt_emloyer', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО сотрудника')),
                ('bt_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('bt_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Приказ о командировке',
                'verbose_name_plural': 'Приказы о командировках',
                'ordering': ['bt_number'],
            },
        ),
    ]
