# Generated by Django 3.1.2 on 2020-10-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutBoundDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(db_index=True, help_text='Введите название документа', max_length=100, verbose_name='Название')),
                ('doc_number', models.CharField(db_index=True, help_text='Введите номер документа', max_length=256, verbose_name='Номер документа')),
                ('doc_date', models.DateField(db_index=True, help_text='Введите дату документа', verbose_name='Дата документа')),
                ('doc_dest', models.CharField(help_text='Введите адресата', max_length=256, verbose_name='Получатель (адресат)')),
                ('doc_content', models.CharField(help_text='Введите краткое документа', max_length=100, verbose_name='Содержание документа')),
                ('doc_reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Исходящие документы',
                'ordering': ['doc_reg_date'],
            },
        ),
    ]
