# Generated by Django 3.1.7 on 2022-04-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(db_index=True, help_text='Введите название подразделения', max_length=256, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['dep_name'],
            },
        ),
        migrations.CreateModel(
            name='logs_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Имя события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События логов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewOrdersOnVacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('order_number', models.CharField(blank=True, db_index=True, help_text='Введите номер приказа', max_length=10, verbose_name='Номер приказа')),
                ('res_officer', models.CharField(blank=True, default='database', editable=False, help_text='Сотрудник, который создал приказ ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ на отпуск',
                'verbose_name_plural': 'Приказы на отпуск (новые)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnOtherMatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oom_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=10, verbose_name='Номер приказа')),
                ('oom_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('oom_content', models.CharField(help_text='Введите содержание приказа', max_length=256, verbose_name='Содержание')),
                ('oom_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ по другим вопросам',
                'verbose_name_plural': 'Приказы по другим вопросам',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnPersonnelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Виды ЛС приказов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnVacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oov_number', models.CharField(blank=True, db_index=True, help_text='Введите номер приказа', max_length=10, verbose_name='Номер приказа')),
                ('oov_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('oov_empList', models.TextField(help_text='Введите сотрудников в приказ', verbose_name='Список сотрудников в приказе')),
                ('oov_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ на отпуск',
                'verbose_name_plural': 'Приказы на отпуск',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutBoundDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(db_index=True, default='Письмо', help_text='Введите вид документа (письмо, справка, и.т.д)', max_length=100, verbose_name='Вид')),
                ('doc_number', models.CharField(db_index=True, default='', help_text='Введите номер документа', max_length=10, verbose_name='Номер документа')),
                ('doc_date', models.DateField(db_index=True, help_text='Введите дату документа', verbose_name='Дата документа')),
                ('doc_dest', models.CharField(help_text='Введите адресата', max_length=256, verbose_name='Получатель (адресат)')),
                ('doc_additionalData', models.CharField(default='', help_text='Введите содержание документа', max_length=256, verbose_name='Содержание документа')),
                ('doc_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Исходящий документ',
                'verbose_name_plural': 'Исходящие документы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SickRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.IntegerField(db_index=True, help_text='Введите номер реестра', verbose_name='Номер реестра')),
                ('sr_year', models.IntegerField(db_index=True, default='0', help_text='Год_сервисное_поле', verbose_name='Год. Сервисное поле')),
                ('sr_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который создал реестр ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Реестр больничных листов',
                'verbose_name_plural': 'Реестры больничных листов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SickDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_number', models.CharField(db_index=True, help_text='Введите номер б\\л', max_length=200, unique=True, verbose_name='Номер б\\л')),
                ('sd_emp', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО')),
                ('sd_pos', models.CharField(db_index=True, help_text='Введите должность', max_length=256, verbose_name='Должность')),
                ('sd_dur_from', models.DateField(db_index=True, help_text='Введите дату начала болезни', verbose_name='Дата начала болезни')),
                ('sd_dur_to', models.DateField(db_index=True, help_text='Введите дату окончания болезни', verbose_name='Дата окончания болезни')),
                ('sd_comm', models.CharField(blank=True, default=' ', help_text='Введите примечание', max_length=256, verbose_name='Примечание')),
                ('sd_bound_reg', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.sickregistry', verbose_name='Связанный реестр ')),
                ('sd_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Больничный лист',
                'verbose_name_plural': 'Больничные листы',
                'ordering': ['sd_bound_reg'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOnPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=5, verbose_name='Номер приказа')),
                ('op_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('op_emloyer', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО сотрудника')),
                ('op_content', models.TextField(help_text='Введите содержание', verbose_name='Содержание приказа')),
                ('op_selected', models.BooleanField(default=False, verbose_name='Выделить в списке')),
                ('op_lastcheck', models.BooleanField(default=False, verbose_name='Последний проверенный')),
                ('op_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('op_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
                ('op_type', models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.ordersonpersonneltypes', verbose_name='Вид приказа ')),
            ],
            options={
                'verbose_name': 'Приказ по личному составу',
                'verbose_name_plural': 'Приказы по личному составу',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdersOfBTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=5, verbose_name='Номер приказа')),
                ('bt_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('bt_place', models.CharField(db_index=True, help_text='Введите место командировки', max_length=256, verbose_name='Место командировки')),
                ('bt_emloyer', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО сотрудника')),
                ('bt_dur_from', models.DateField(db_index=True, default='2000-01-01', help_text='Введите дату начала командировки', verbose_name='Дата начала командировки')),
                ('bt_dur_to', models.DateField(db_index=True, default='2000-01-01', help_text='Введите дату завершения командировки', verbose_name='Дата завершения командировки')),
                ('bt_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('bt_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Приказ о командировке',
                'verbose_name_plural': 'Приказы о командировках',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewOrdersOnVacation_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(db_index=True, help_text='ФИО сотрудника', max_length=256, verbose_name='ФИО сотрудника')),
                ('dur_from', models.DateField(db_index=True, help_text='Введите дату начала отпуска', verbose_name='Дата начала отпуска')),
                ('dur_to', models.DateField(db_index=True, help_text='Введите дату окончания отпуска', verbose_name='Дата окончания отпуска')),
                ('days_count', models.CharField(db_index=True, help_text='Количество дней', max_length=5, verbose_name='Количество дней')),
                ('vac_type', models.CharField(choices=[('Очередной', 'Очередной'), ('Пенсионный', 'Пенсионный'), ('Без сохранения ЗП', 'Без сохранения ЗП'), ('Учебный', 'Учебный'), ('Донор', 'Донор'), ('С сохр. ЗП', 'С сохр. ЗП')], db_index=True, help_text='Вид отпуска', max_length=256, verbose_name='Вид отпуска')),
                ('comm', models.CharField(blank=True, db_index=True, help_text='Комментарий', max_length=256, null=True, verbose_name='Комментарий')),
                ('bound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.newordersonvacation', verbose_name='Приказ ')),
                ('dep', models.ForeignKey(default='79', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Сотрудник в приказе на отпуск',
                'verbose_name_plural': 'Сотрудники в приказах на отпуск',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата события')),
                ('doc_id', models.IntegerField(verbose_name='Связанный документ')),
                ('type', models.CharField(max_length=100, verbose_name='Вид документа')),
                ('number', models.CharField(default=0, max_length=100, verbose_name='Номер документа')),
                ('doc_date', models.DateField(db_index=True, default='2000-01-01', verbose_name='Дата документа')),
                ('link', models.CharField(default='', max_length=256, verbose_name='Ссылка')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год')),
                ('addData', models.CharField(blank=True, max_length=256, verbose_name='Дополнительная информация')),
                ('res_officer', models.CharField(blank=True, max_length=256, verbose_name='Ответственный')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.logs_event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Логи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LetterOfResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lor_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('lor_number', models.CharField(db_index=True, default='', help_text='Введите номер документа', max_length=10, verbose_name='Номер документа')),
                ('lor_employee', models.CharField(help_text='Введите ФИО увольняемого сотрудника', max_length=256, verbose_name='Увольняемый сотрудник')),
                ('lor_position', models.CharField(help_text='Введите должность увольняемого сотрудника', max_length=256, verbose_name='Должность')),
                ('lor_dateOfRes', models.DateField(db_index=True, help_text='Введите дату увольнения', verbose_name='Дата увольнения')),
                ('lor_additionalData', models.CharField(blank=True, default='', help_text='Введите примечание', max_length=256, null=True, verbose_name='Примечание')),
                ('lor_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('lor_departament', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LetterOfInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('loi_number', models.CharField(db_index=True, default='', help_text='Введите номер документа', max_length=10, verbose_name='Номер документа')),
                ('loi_employee', models.CharField(help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='Принимаемый сотрудник')),
                ('loi_position', models.CharField(help_text='Введите должность принимаемого сотрудника', max_length=256, verbose_name='Должность')),
                ('loi_dateOfInv', models.DateField(blank=True, db_index=True, help_text='Введите дату начала работы', null=True, verbose_name='Дата начала работы')),
                ('loi_additionalData', models.CharField(blank=True, default=' ', help_text='Введите примечание', max_length=256, verbose_name='Примечание')),
                ('loi_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('loi_department', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Заявление на прием',
                'verbose_name_plural': 'Заявления на прием',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(db_index=True, help_text='Введите номер договора', max_length=256, verbose_name='Номер договора')),
                ('lc_date', models.DateField(db_index=True, help_text='Введите дату договора', verbose_name='Дата договора')),
                ('lc_emloyer', models.CharField(db_index=True, help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='ФИО принимаемого сотрудника')),
                ('lc_pos', models.CharField(db_index=True, default=' ', help_text='Введите должность', max_length=256, verbose_name='Должность')),
                ('lc_dateOfInv', models.DateField(db_index=True, help_text='Введите дату приема на работу', verbose_name='Дата приема на работу')),
                ('lc_workCond', models.TextField(db_index=True, help_text='Введите условие работы', verbose_name='Условие работы')),
                ('lc_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('lc_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Трудовой договор',
                'verbose_name_plural': 'Трудовые договоры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, verbose_name='Номер удостоверения')),
                ('date_giving', models.DateField(db_index=True, help_text='Введите дату выдачи удостоверения', verbose_name='Дата выдачи удостоверения')),
                ('employer', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='Сотрудник')),
                ('res_officer', models.CharField(blank=True, default='database', editable=False, help_text='Сотрудник, который занес запись', max_length=256, verbose_name='Ответственный сотрудник')),
                ('department', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Удостоверение',
                'verbose_name_plural': 'Удостоверения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_number', models.CharField(db_index=True, help_text='Введите номер трудовой книжки', max_length=256, verbose_name='Номер\\серия')),
                ('eh_dateOfInv', models.DateField(db_index=True, help_text='Введите дату приема на работу', verbose_name='Дата приема на работу')),
                ('eh_employer', models.CharField(db_index=True, help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='ФИО принимаемого сотрудника')),
                ('eh_pos', models.CharField(db_index=True, help_text='Введите должность', max_length=256, verbose_name='Должность')),
                ('eh_OrderInv', models.CharField(db_index=True, help_text='Введите номер приказа о приеме', max_length=256, verbose_name='Приказ о приеме на работу:')),
                ('eh_OrderResign', models.CharField(blank=True, db_index=True, help_text='Введите номер приказа об увольнении', max_length=256, null=True, verbose_name='Приказ об увольнении:')),
                ('eh_dateOfResign', models.DateField(blank=True, db_index=True, help_text='Введите дату увольнения', null=True, verbose_name='Дата увольнения')),
                ('eh_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('eh_isdigital', models.BooleanField(blank=True, default=False, null=True, verbose_name='Электронная')),
                ('eh_dep', models.ForeignKey(default='79', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Трудовая книжка',
                'verbose_name_plural': 'Трудовые книжки',
                'ordering': ['-id'],
            },
        ),
    ]
