# Generated by Django 3.1.7 on 2022-03-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Имя события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События логов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ordersonpersonnel',
            name='op_type',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.ordersonpersonneltypes', verbose_name='Вид приказа '),
        ),
    ]
