# Generated by Django 3.1.7 on 2022-08-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='days_count',
            field=models.CharField(blank=True, db_index=True, help_text='Количество дней', max_length=5, null=True, verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='dur_from',
            field=models.DateField(blank=True, db_index=True, help_text='Введите дату начала отпуска', null=True, verbose_name='Дата начала отпуска'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='dur_to',
            field=models.DateField(blank=True, db_index=True, help_text='Введите дату окончания отпуска', null=True, verbose_name='Дата окончания отпуска'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='vac_type',
            field=models.CharField(choices=[('Очередной', 'Очередной'), ('Пенсионный', 'Пенсионный'), ('Без сохранения ЗП', 'Без сохранения ЗП'), ('Учебный', 'Учебный'), ('Донор', 'Донор'), ('С сохр. ЗП', 'С сохр. ЗП'), ('Отменен', 'Отменен')], db_index=True, help_text='Вид отпуска', max_length=256, verbose_name='Вид отпуска'),
        ),
    ]
