# Generated by Django 4.2.15 on 2024-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='Владелец')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Число')),
                ('bolean', models.BooleanField(default=False, verbose_name='Булево')),
                ('flt', models.FloatField(blank=True, null=True, verbose_name='Десятичное значение')),
            ],
            options={
                'verbose_name': 'Дополнительный реквезит',
                'verbose_name_plural': 'Дополнительные реквезиты',
                'ordering': ['id', 'owner'],
            },
        ),
    ]
