# Generated by Django 3.1.2 on 2020-10-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('loi_employee', models.CharField(help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='Принимаемый сотрудник')),
                ('loi_position', models.CharField(help_text='Введите должность принимаемого сотрудника', max_length=256, verbose_name='Должность')),
                ('loi_department', models.CharField(help_text='Введите подразделение принимаемого сотрудника', max_length=256, verbose_name='Подразделение')),
                ('loi_dateOfInv', models.DateField(blank=True, db_index=True, help_text='Введите дату начала работы', null=True, verbose_name='Дата начала работы')),
                ('loi_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на прием',
                'verbose_name_plural': 'Заявления на прием',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LetterOfResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lor_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('lor_employee', models.CharField(help_text='Введите ФИО увольняемого сотрудника', max_length=256, verbose_name='Увольняемый сотрудник')),
                ('lor_position', models.CharField(help_text='Введите должность увольняемого сотрудника', max_length=256, verbose_name='Должность')),
                ('lor_departament', models.CharField(help_text='Введите подразделение увольняемого сотрудника', max_length=256, verbose_name='Подразделение')),
                ('lor_dateOfRes', models.DateField(db_index=True, help_text='Введите дату увольнения', verbose_name='Дата увольнения')),
                ('lor_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='outbounddocument',
            options={'ordering': ['id'], 'verbose_name': 'Исходящий документ', 'verbose_name_plural': 'Исходящие документы'},
        ),
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_content',
        ),
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_name',
        ),
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_number',
        ),
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_reg_date',
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='doc_additionalData',
            field=models.CharField(default='none', help_text='Введите содержание документа', max_length=256, verbose_name='Содержание документа'),
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='doc_res_officer',
            field=models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник'),
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='doc_type',
            field=models.CharField(db_index=True, default='Письмо', help_text='Введите вид документа (письмо, справка, и.т.д)', max_length=100, verbose_name='Вид'),
        ),
    ]
