# Generated by Django 3.1.7 on 2022-03-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0002_auto_20220329_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата события'),
        ),
    ]
