# Generated by Django 3.1.2 on 2020-10-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0002_auto_20201023_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersOnOtherMatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oom_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=5, verbose_name='Номер приказа')),
                ('oom_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('oom_content', models.CharField(help_text='Введите содержание приказа', max_length=256, verbose_name='Содержание')),
                ('oom_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ по другим вопросам',
                'verbose_name_plural': 'Приказы по другим вопросам',
                'ordering': ['id'],
            },
        ),
    ]
