# Generated by Django 3.1.7 on 2022-03-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0002_auto_20220325_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата события')),
                ('doc_id', models.IntegerField(verbose_name='Связанный документ')),
                ('type', models.CharField(max_length=100, verbose_name='Вид документа')),
                ('number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('doc_date', models.DateField(db_index=True, default='01.01.2000', verbose_name='Дата документа')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год')),
                ('addData', models.CharField(blank=True, max_length=256, verbose_name='Дополнительная информация')),
                ('res_officer', models.CharField(blank=True, max_length=256, verbose_name='Ответственный')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.logs_event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Логи',
                'ordering': ['-date'],
            },
        ),
    ]
