# Generated by Django 3.1.2 on 2020-12-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0003_laborcontract_lc_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_number', models.CharField(db_index=True, help_text='Введите номер трудовой книжки', max_length=256, verbose_name='Номер\\серия')),
                ('eh_dateOfInv', models.DateField(db_index=True, help_text='Введите дату приема на работу', verbose_name='Дата приема на работу')),
                ('eh_employer', models.CharField(db_index=True, help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='ФИО принимаемого сотрудника')),
                ('eh_pos', models.CharField(db_index=True, help_text='Введите должность', max_length=256, verbose_name='Должность')),
                ('eh_OrderInv', models.CharField(db_index=True, help_text='Введите номер приказа о приеме', max_length=256, verbose_name='Приказ о приеме на работу:')),
                ('eh_OrderResign', models.CharField(blank=True, db_index=True, help_text='Введите номер приказа об увольнении', max_length=256, verbose_name='Приказ об увольнении:')),
                ('eh_dateOfReturn', models.DateField(blank=True, db_index=True, help_text='Введите дату выдачи на руки', verbose_name='Дата выдачи на руки')),
                ('eh_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
                ('eh_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
        ),
    ]
