# Generated by Django 3.1.2 on 2020-10-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0003_ordersonothermatters'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofresignation',
            name='lor_additionalData',
            field=models.CharField(default='примечание', help_text='Введите примечание', max_length=256, verbose_name='Примечание'),
        ),
    ]
