# Generated by Django 3.1.2 on 2020-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0004_employmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='eh_OrderResign',
            field=models.CharField(blank=True, db_index=True, help_text='Введите номер приказа об увольнении', max_length=256, null=True, verbose_name='Приказ об увольнении:'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='eh_dateOfReturn',
            field=models.DateField(blank=True, db_index=True, help_text='Введите дату выдачи на руки', null=True, verbose_name='Дата выдачи на руки'),
        ),
    ]
