# Generated by Django 3.1.2 on 2020-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0004_letterofresignation_lor_additionaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersOnVacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oov_number', models.CharField(db_index=True, help_text='Введите номер приказа', max_length=6, verbose_name='Номер приказа')),
                ('oov_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('oov_empList', models.TextField(help_text='Введите сотрудников в приказ', verbose_name='Список сотрудников в приказе')),
                ('oov_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Приказ на отпуск',
                'verbose_name_plural': 'Приказы на отпуск',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_additionalData',
            field=models.CharField(blank=True, default='примечание', help_text='Введите примечание', max_length=256, verbose_name='Примечание'),
        ),
    ]
