# Generated by Django 3.1.2 on 2020-10-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0004_outbounddocument_doc_additionaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outbounddocument',
            options={'ordering': ['-doc_date'], 'verbose_name': 'Исходящий документ', 'verbose_name_plural': 'Исходящие документы'},
        ),
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_reg_date',
        ),
    ]
