# Generated by Django 3.1.7 on 2022-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0004_auto_20220325_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='doc_date',
            field=models.DateField(db_index=True, default='2000-01-01', verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='logs',
            name='number',
            field=models.CharField(default=0, max_length=100, verbose_name='Номер документа'),
        ),
    ]
