# Generated by Django 4.1.1 on 2022-09-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0005_auto_20220905_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersonpersonnel',
            name='op_dateOfRes',
            field=models.DateField(blank=True, db_index=True, default='0001-01-01', help_text='Введите дату увольнения', null=True, verbose_name='Дата увольнения'),
        ),
    ]
