# Generated by Django 3.1.7 on 2022-03-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0005_ordersonpersonnel_op_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersonpersonnel',
            name='op_date',
        ),
    ]
