# Generated by Django 3.1.2 on 2020-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0005_auto_20201209_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersonvacation',
            name='oov_number',
            field=models.CharField(db_index=True, help_text='Введите номер приказа', max_length=8, verbose_name='Номер приказа'),
        ),
    ]
