# Generated by Django 3.1.2 on 2020-10-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0005_auto_20201012_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddocument',
            name='doc_additionalData',
            field=models.CharField(help_text='Введите дополнительную информацию по документу (необязательно)', max_length=256, verbose_name='Дополнительная информация'),
        ),
    ]
