# Generated by Django 3.1.7 on 2022-03-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0005_auto_20220325_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='link',
            field=models.CharField(default='', max_length=256, verbose_name='Ссылка'),
        ),
    ]
