# Generated by Django 4.1.1 on 2023-03-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0006_ordersonpersonnel_op_dateofres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersonpersonnel',
            options={'ordering': ['-op_date'], 'verbose_name': 'Приказ по личному составу', 'verbose_name_plural': 'Приказы по личному составу'},
        ),
    ]
