# Generated by Django 3.1.2 on 2020-10-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0006_auto_20201013_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_name',
        ),
        migrations.RemoveField(
            model_name='outbounddocument',
            name='doc_number',
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='doc_res_officer',
            field=models.CharField(default='none', help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник'),
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='doc_type',
            field=models.CharField(db_index=True, default='Письмо', help_text='Введите вид документа (письмо, справка, и.т.д)', max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='outbounddocument',
            name='doc_additionalData',
            field=models.CharField(help_text='Введите содержание документа', max_length=256, verbose_name='Содержание документа'),
        ),
    ]
