# Generated by Django 4.1.1 on 2023-04-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0007_alter_ordersonpersonnel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOfResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите основание увольнения', max_length=200, verbose_name='Основание увольнения')),
            ],
            options={
                'verbose_name': 'Основание увольнения',
                'verbose_name_plural': 'Основания увольнения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='letterofresignation',
            name='lor_itemOfRes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.itemofresignation', verbose_name='Основание увольнения'),
        ),
    ]
