# Generated by Django 3.1.2 on 2020-12-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0008_auto_20201224_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outbounddocument',
            options={'ordering': ['doc_number'], 'verbose_name': 'Исходящий документ', 'verbose_name_plural': 'Исходящие документы'},
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='doc_number',
            field=models.CharField(db_index=True, default='', help_text='Введите номер документа', max_length=10, verbose_name='Номер документа'),
        ),
    ]
