# Generated by Django 3.1.2 on 2020-10-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0008_auto_20201014_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outbounddocument',
            options={'ordering': ['-id'], 'verbose_name': 'Исходящий документ', 'verbose_name_plural': 'Исходящие документы'},
        ),
    ]
