# Generated by Django 4.1.1 on 2023-04-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0009_alter_logs_adddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_additionalData',
            field=models.CharField(blank=True, help_text='Введите примечание', max_length=256, null=True, verbose_name='Примечание'),
        ),
    ]
