# Generated by Django 3.1.2 on 2020-12-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0009_auto_20201224_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcontract',
            name='lc_dep',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
    ]
