# Generated by Django 3.1.2 on 2020-12-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0010_auto_20201224_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterofresignation',
            options={'ordering': ['lor_number'], 'verbose_name': 'Заявление на увольнение', 'verbose_name_plural': 'Заявления на увольнение'},
        ),
        migrations.AddField(
            model_name='letterofresignation',
            name='lor_number',
            field=models.CharField(db_index=True, default='', help_text='Введите номер документа', max_length=10, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_departament',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
    ]
