# Generated by Django 4.1.1 on 2023-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0010_alter_letterofresignation_lor_additionaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='invite_checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkinDate', models.DateTimeField(help_text='Введите дату записи на прием', verbose_name='Время записи на прием')),
                ('citizen', models.CharField(max_length=150, verbose_name='ФИО гражданина (гражданки)')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Запись отменена')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Журнал записей на прием',
                'ordering': ['checkinDate'],
            },
        ),
    ]
