# Generated by Django 3.1.2 on 2020-10-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0010_auto_20201016_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbounddocument',
            name='doc_res_officer',
            field=models.CharField(blank=True, default='none', editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник'),
        ),
    ]
