# Generated by Django 3.1.2 on 2020-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0011_auto_20201224_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterofinvite',
            options={'ordering': ['loi_number'], 'verbose_name': 'Заявление на прием', 'verbose_name_plural': 'Заявления на прием'},
        ),
        migrations.AddField(
            model_name='letterofinvite',
            name='loi_number',
            field=models.CharField(db_index=True, default='', help_text='Введите номер документа', max_length=10, verbose_name='Номер документа'),
        ),
    ]
