# Generated by Django 4.1.1 on 2023-07-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0011_invite_checkin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invite_checkin',
            new_name='inviteCheckin_model',
        ),
    ]
