# Generated by Django 4.1.1 on 2024-07-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('reg_jounals', '0012_rename_invite_checkin_invitecheckin_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='department',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='identity',
            name='bound_employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.employers'),
        ),
        migrations.AddField(
            model_name='identity',
            name='department_new',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='identity',
            name='department_old',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='bound_employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.employers'),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.position'),
        ),
        migrations.AddField(
            model_name='letterofinvite',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='letterofinvite',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.position'),
        ),
        migrations.AddField(
            model_name='letterofresignation',
            name='bound_employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.employers'),
        ),
        migrations.AddField(
            model_name='letterofresignation',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='letterofresignation',
            name='position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.position'),
        ),
        migrations.AddField(
            model_name='newordersonvacation_item',
            name='bound_employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.employers'),
        ),
        migrations.AddField(
            model_name='newordersonvacation_item',
            name='department_new',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='ordersofbtrip',
            name='bound_employer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.employers'),
        ),
        migrations.AddField(
            model_name='ordersofbtrip',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department'),
        ),
        migrations.AddField(
            model_name='ordersonpersonnel',
            name='bound_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.employers', verbose_name='Связанный работник'),
        ),
        migrations.AddField(
            model_name='ordersonpersonnel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='ordersonpersonnel',
            name='grounds_for_resignation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.itemofresignation', verbose_name='Основание увольнения'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='eh_dep',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='eh_pos',
            field=models.CharField(blank=True, db_index=True, help_text='Введите должность', max_length=256, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='employer',
            field=models.CharField(blank=True, db_index=True, help_text='Введите ФИО сотрудника', max_length=256, null=True, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='lc_dep',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='lc_emloyer',
            field=models.CharField(blank=True, db_index=True, help_text='Введите ФИО принимаемого сотрудника', max_length=256, null=True, verbose_name='ФИО принимаемого сотрудника'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='lc_pos',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Введите должность', max_length=256, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='lc_workCond',
            field=models.TextField(db_index=True, help_text='Введите условие работы', verbose_name='Условия работы'),
        ),
        migrations.AlterField(
            model_name='letterofinvite',
            name='loi_department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='letterofinvite',
            name='loi_position',
            field=models.CharField(blank=True, help_text='Введите должность принимаемого сотрудника', max_length=256, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_additionalData',
            field=models.CharField(blank=True, default=None, help_text='Введите примечание', max_length=256, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_departament',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_employee',
            field=models.CharField(blank=True, help_text='Введите ФИО увольняемого сотрудника', max_length=256, null=True, verbose_name='Увольняемый сотрудник'),
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_position',
            field=models.CharField(blank=True, help_text='Введите должность увольняемого сотрудника', max_length=256, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='dep',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='dur_from',
            field=models.DateField(blank=True, db_index=True, help_text='Введите дату начала отпуска', null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='dur_to',
            field=models.DateField(blank=True, db_index=True, help_text='Введите дату окончания отпуска', null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='fio',
            field=models.CharField(blank=True, db_index=True, help_text='ФИО сотрудника', max_length=256, null=True, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='ordersofbtrip',
            name='bt_dep',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='ordersofbtrip',
            name='bt_emloyer',
            field=models.CharField(blank=True, db_index=True, help_text='Введите ФИО сотрудника', max_length=256, null=True, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='ordersonpersonnel',
            name='op_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
        migrations.AlterField(
            model_name='ordersonpersonnel',
            name='op_emloyer',
            field=models.CharField(blank=True, db_index=True, help_text='Введите ФИО сотрудника', max_length=256, null=True, verbose_name='ФИО сотрудника'),
        ),
    ]
