# Generated by Django 3.1.2 on 2020-12-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0012_auto_20201224_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofinvite',
            name='loi_department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
    ]
