# Generated by Django 3.1.2 on 2020-10-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0012_auto_20201019_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lor_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('lor_employee', models.CharField(help_text='Введите ФИО увольняемого сотрудника', max_length=256, verbose_name='Увольняемый сотрудник')),
                ('lor_position', models.CharField(help_text='Введите должность увольняемого сотрудника', max_length=256, verbose_name='Должность')),
                ('lor_departament', models.CharField(help_text='Введите подразделение увольняемого сотрудника', max_length=256, verbose_name='Подразделение')),
                ('lor_dateOfRes', models.DateField(db_index=True, help_text='Введите дату увольнения', verbose_name='Дата увольнения')),
                ('lor_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на увольнение',
                'verbose_name_plural': 'Заявления на увольнение',
                'ordering': ['id'],
            },
        ),
    ]
