# Generated by Django 3.1.2 on 2020-10-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0013_letterofresignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loi_date', models.DateField(db_index=True, help_text='Введите дату поступления заявления', verbose_name='Дата поступления заявления')),
                ('loi_employee', models.CharField(help_text='Введите ФИО принимаемого сотрудника', max_length=256, verbose_name='Принимаемый сотрудник')),
                ('loi_position', models.CharField(help_text='Введите должность принимаемого сотрудника', max_length=256, verbose_name='Должность')),
                ('loi_department', models.CharField(help_text='Введите подразделение принимаемого сотрудника', max_length=256, verbose_name='Подразделение')),
                ('loi_dateOfInv', models.DateField(blank=True, db_index=True, help_text='Введите дату начала работы', verbose_name='Дата начала работы')),
                ('loi_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который внес документ в систему ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Заявление на прием',
                'verbose_name_plural': 'Заявления на прием',
                'ordering': ['id'],
            },
        ),
    ]
