# Generated by Django 3.1.2 on 2020-12-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0013_auto_20201224_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersofbtrip',
            name='bt_dur_from',
            field=models.DateField(db_index=True, default='2000-01-01', help_text='Введите дату начала командировки', verbose_name='Дата начала командировки'),
        ),
        migrations.AddField(
            model_name='ordersofbtrip',
            name='bt_dur_to',
            field=models.DateField(db_index=True, default='2000-01-01', help_text='Введите дату завершения командировки', verbose_name='Дата завершения командировки'),
        ),
    ]
