# Generated by Django 3.1.2 on 2020-12-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0014_auto_20201225_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcontract',
            name='lc_workCond',
            field=models.TextField(db_index=True, help_text='Введите условие работы', verbose_name='Условие работы'),
        ),
    ]
