# Generated by Django 3.1.2 on 2020-10-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0014_letterofinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofinvite',
            name='loi_dateOfInv',
            field=models.DateField(blank=True, db_index=True, help_text='Введите дату начала работы', null=True, verbose_name='Дата начала работы'),
        ),
    ]
