# Generated by Django 3.1.2 on 2020-12-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0015_auto_20201225_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofinvite',
            name='loi_additionalData',
            field=models.CharField(blank=True, default='примечание', help_text='Введите примечание', max_length=256, verbose_name='Примечание'),
        ),
    ]
