# Generated by Django 3.1.2 on 2020-12-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0016_letterofinvite_loi_additionaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersonpersonnel',
            options={'ordering': ['id'], 'verbose_name': 'Приказ по личному составу', 'verbose_name_plural': 'Приказы по личному составу'},
        ),
    ]
