# Generated by Django 3.1.2 on 2020-12-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0017_auto_20201228_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborcontract',
            options={'ordering': ['id'], 'verbose_name': 'Трудовой договор', 'verbose_name_plural': 'Трудовые договоры'},
        ),
        migrations.AlterModelOptions(
            name='letterofinvite',
            options={'ordering': ['id'], 'verbose_name': 'Заявление на прием', 'verbose_name_plural': 'Заявления на прием'},
        ),
        migrations.AlterModelOptions(
            name='letterofresignation',
            options={'ordering': ['id'], 'verbose_name': 'Заявление на увольнение', 'verbose_name_plural': 'Заявления на увольнение'},
        ),
        migrations.AlterModelOptions(
            name='ordersofbtrip',
            options={'ordering': ['id'], 'verbose_name': 'Приказ о командировке', 'verbose_name_plural': 'Приказы о командировках'},
        ),
        migrations.AlterModelOptions(
            name='outbounddocument',
            options={'ordering': ['id'], 'verbose_name': 'Исходящий документ', 'verbose_name_plural': 'Исходящие документы'},
        ),
    ]
