# Generated by Django 3.1.2 on 2020-12-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0018_auto_20201228_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.IntegerField(db_index=True, help_text='Введите номер реестра', verbose_name='Номер реестра')),
                ('sr_res_officer', models.CharField(blank=True, editable=False, help_text='Сотрудник, который создал реестр ', max_length=256, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Реестр больничных листов',
                'verbose_name_plural': 'Реестры больничных листов',
                'ordering': ['sr_number'],
            },
        ),
        migrations.CreateModel(
            name='SickDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_number', models.CharField(db_index=True, help_text='Введите номер б\\л', max_length=256, verbose_name='Номер б\\л')),
                ('sd_emp', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО')),
                ('sd_pos', models.CharField(db_index=True, help_text='Введите должность', max_length=256, verbose_name='Должность')),
                ('sd_dur_from', models.DateField(db_index=True, help_text='Введите дату начала болезни', verbose_name='Дата начала болезни')),
                ('sd_dur_to', models.DateField(db_index=True, help_text='Введите дату окончания болезни', verbose_name='Дата окончания болезни')),
                ('sd_comm', models.CharField(blank=True, default=' ', help_text='Введите примечание', max_length=256, verbose_name='Примечание')),
                ('sd_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
                ('sd_reg_number', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.sickregistry', verbose_name='№ реестра ')),
            ],
            options={
                'verbose_name': 'Больничный лист',
                'verbose_name_plural': 'Больничные листы',
                'ordering': ['sd_reg_number__sr_number'],
            },
        ),
    ]
