# Generated by Django 3.1.2 on 2020-12-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0018_auto_20201228_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_number', models.CharField(db_index=True, help_text='Введите номер реестра', max_length=256, verbose_name='Номер реестра')),
                ('sk_date', models.DateField(db_index=True, help_text='Введите дату реестра', verbose_name='Дата реестра')),
                ('sk_rnumber', models.CharField(db_index=True, help_text='Введите номер б\\л', max_length=256, verbose_name='Номер б\\л')),
                ('sk_emp', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='ФИО')),
                ('sk_pos', models.CharField(db_index=True, help_text='Введите должность', max_length=256, verbose_name='Должность')),
                ('sk_dur_from', models.DateField(db_index=True, help_text='Введите дату начала болезни', verbose_name='Дата начала болезни')),
                ('sk_dur_to', models.DateField(db_index=True, help_text='Введите дату окончания болезни', verbose_name='Дата окончания болезни')),
                ('sk_dep', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Больничный лист',
                'verbose_name_plural': 'Больничные листы',
                'ordering': ['id'],
            },
        ),
    ]
