# Generated by Django 3.1.2 on 2020-12-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0019_sicklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicklist',
            name='sk_comm',
            field=models.CharField(blank=True, default='примечание', help_text='Введите примечание', max_length=256, verbose_name='Примечание'),
        ),
    ]
