# Generated by Django 3.1.2 on 2020-12-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0019_sickdocument_sickregistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sickdocument',
            options={'ordering': ['sd_reg_number'], 'verbose_name': 'Больничный лист', 'verbose_name_plural': 'Больничные листы'},
        ),
        migrations.AlterField(
            model_name='sickdocument',
            name='sd_reg_number',
            field=models.CharField(blank=True, default=' ', help_text='Введите номер реестра', max_length=256, verbose_name='№ реестра '),
        ),
    ]
