# Generated by Django 3.1.2 on 2020-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0020_sicklist_sk_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicklist',
            name='sk_comm',
            field=models.CharField(blank=True, default=' ', help_text='Введите примечание', max_length=256, verbose_name='Примечание'),
        ),
    ]
