# Generated by Django 3.1.2 on 2021-01-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0020_auto_20201230_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersonpersonnel',
            name='op_selected',
            field=models.BooleanField(default=False, verbose_name='Выделить в списке'),
        ),
    ]
