# Generated by Django 3.1.2 on 2020-12-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0021_auto_20201229_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicklist',
            name='sk_number',
            field=models.IntegerField(db_index=True, help_text='Введите номер реестра', verbose_name='Номер реестра'),
        ),
    ]
