# Generated by Django 3.1.2 on 2021-01-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0021_ordersonpersonnel_op_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='eh_OrderResign',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Введите номер приказа об увольнении', max_length=256, null=True, verbose_name='Приказ об увольнении:'),
        ),
    ]
