# Generated by Django 3.1.2 on 2021-01-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0022_auto_20210118_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrdersOnVacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True, help_text='Введите дату приказа', verbose_name='Дата приказа')),
                ('order_number', models.CharField(blank=True, db_index=True, help_text='Введите номер приказа', max_length=10, verbose_name='Номер приказа')),
            ],
            options={
                'verbose_name': 'Приказ на отпуск',
                'verbose_name_plural': 'Приказы на отпуск',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='eh_OrderResign',
            field=models.CharField(blank=True, db_index=True, help_text='Введите номер приказа об увольнении', max_length=256, null=True, verbose_name='Приказ об увольнении:'),
        ),
        migrations.CreateModel(
            name='NewOrdersOnVacation_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_order', models.CharField(blank=True, db_index=True, help_text='Номер связанного приказа', max_length=10, verbose_name='Номер связанного приказа')),
                ('fio', models.CharField(db_index=True, help_text='ФИО сотрудника', max_length=256, verbose_name='ФИО сотрудника')),
                ('dur_from', models.DateField(db_index=True, help_text='Введите дату начала отпуска', verbose_name='Дата начала отпуска')),
                ('dur_to', models.DateField(db_index=True, help_text='Введите дату окончания отпуска', verbose_name='Дата окончания отпуска')),
                ('days_count', models.CharField(db_index=True, help_text='Количество дней', max_length=5, verbose_name='Количество дней')),
                ('vac_type', models.CharField(choices=[('Очердной', 'Очередной'), ('Пенсионный', 'Пенсионный'), ('Без сохранения ЗП', 'Без сохранения ЗП')], db_index=True, help_text='Вид отпуска', max_length=256, verbose_name='Количество дней')),
                ('comm', models.CharField(db_index=True, help_text='Комментарий', max_length=256, verbose_name='Комментарий')),
                ('dep', models.ForeignKey(default='79', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение ')),
            ],
            options={
                'verbose_name': 'Сотрудник в приказе на отпуск',
                'verbose_name_plural': 'Сотрудниуи в приказах на отпуск',
                'ordering': ['id'],
            },
        ),
    ]
