# Generated by Django 3.1.2 on 2020-12-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0022_auto_20201229_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sicklist',
            options={'ordering': ['sk_number'], 'verbose_name': 'Больничный лист', 'verbose_name_plural': 'Больничные листы'},
        ),
    ]
