# Generated by Django 3.1.2 on 2020-12-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0023_auto_20201229_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicklist',
            name='sk_date',
        ),
    ]
