# Generated by Django 3.1.2 on 2021-01-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0024_newordersonvacation_res_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='comm',
            field=models.CharField(blank=True, db_index=True, help_text='Комментарий', max_length=256, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='vac_type',
            field=models.CharField(choices=[('Очердной', 'Очередной'), ('Пенсионный', 'Пенсионный'), ('Без сохранения ЗП', 'Без сохранения ЗП')], db_index=True, help_text='Вид отпуска', max_length=256, verbose_name='Вид отпуска'),
        ),
    ]
