# Generated by Django 3.1.2 on 2021-01-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0025_auto_20210120_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newordersonvacation_item',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудник в приказе на отпуск', 'verbose_name_plural': 'Сотрудники в приказах на отпуск'},
        ),
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_additionalData',
            field=models.CharField(blank=True, default='примечание', help_text='Введите примечание', max_length=256, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='vac_type',
            field=models.CharField(choices=[('Очередной', 'Очередной'), ('Пенсионный', 'Пенсионный'), ('Без сохранения ЗП', 'Без сохранения ЗП')], db_index=True, help_text='Вид отпуска', max_length=256, verbose_name='Вид отпуска'),
        ),
    ]
