# Generated by Django 3.1.2 on 2021-01-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0026_auto_20210125_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofresignation',
            name='lor_additionalData',
            field=models.CharField(blank=True, default=' ', help_text='Введите примечание', max_length=256, null=True, verbose_name='Примечание'),
        ),
    ]
