# Generated by Django 3.1.2 on 2021-02-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0029_auto_20210201_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newordersonvacation_item',
            name='bound_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.newordersonvacation', verbose_name='Приказ '),
        ),
    ]
