# Generated by Django 3.1.2 on 2021-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0031_auto_20210202_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newordersonvacation',
            options={'ordering': ['-id'], 'verbose_name': 'Приказ на отпуск', 'verbose_name_plural': 'Приказы на отпуск (новые)'},
        ),
        migrations.AlterField(
            model_name='letterofinvite',
            name='loi_additionalData',
            field=models.CharField(blank=True, default=' ', help_text='Введите примечание', max_length=256, verbose_name='Примечание'),
        ),
    ]
