# Generated by Django 3.1.2 on 2021-02-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0032_auto_20210202_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'ordering': ['-id'], 'verbose_name': 'Трудовая книжка', 'verbose_name_plural': 'Трудовые книжки'},
        ),
    ]
