# Generated by Django 3.1.2 on 2021-03-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0033_auto_20210202_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersonpersonnel',
            name='op_lastcheck',
            field=models.BooleanField(default=False, verbose_name='Последний проверенный'),
        ),
    ]
