# Generated by Django 3.1.2 on 2021-03-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0034_ordersonpersonnel_op_lastcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер удостоверения')),
                ('date_giving', models.DateField(db_index=True, help_text='Введите дату выдачи удостоверения', verbose_name='Дата выдачи удостоверения')),
                ('employer', models.CharField(db_index=True, help_text='Введите ФИО сотрудника', max_length=256, verbose_name='Сотрудник')),
                ('res_officer', models.CharField(blank=True, default='database', editable=False, help_text='Сотрудник, который занес запись', max_length=256, verbose_name='Ответственный сотрудник')),
                ('department', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Удостоверение',
                'verbose_name_plural': 'Удостоверения',
                'ordering': ['-id'],
            },
        ),
    ]
