# Generated by Django 3.1.2 on 2021-03-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0035_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='Номер удостоверения'),
        ),
    ]
