# Generated by Django 3.1.7 on 2022-04-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0001_initial'),
        ('VacShed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantionSheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur_from', models.DateField(verbose_name='Период с')),
                ('dur_to', models.DateField(verbose_name='Период по')),
                ('days_count', models.IntegerField(verbose_name='Количество дней')),
                ('bound_shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VacShed.vacantionshedule')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.employers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Элемент графика',
                'verbose_name_plural': 'Элементы графика',
                'ordering': ['bound_shed'],
            },
        ),
    ]
