# Generated by Django 3.1.7 on 2022-04-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacShed', '0002_vacantionsheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionshedule',
            name='res_officer',
            field=models.CharField(default='', max_length=256, verbose_name='Ответственный'),
        ),
    ]
