# Generated by Django 3.1.7 on 2022-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacShed', '0003_vacantionshedule_res_officer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacantionsheduleitem',
            options={'ordering': ['-bound_shed__year'], 'verbose_name': 'Элемент графика', 'verbose_name_plural': 'Элементы графика'},
        ),
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='child_year',
            field=models.CharField(default='', max_length=4, null=True, verbose_name='Год рож-я иждевенца: '),
        ),
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='city',
            field=models.CharField(default='', max_length=254, null=True, verbose_name='Проезд: '),
        ),
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='days_count_move',
            field=models.IntegerField(null=True, verbose_name='Кол-во дней после переноса '),
        ),
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='move_from',
            field=models.DateField(default='', null=True, verbose_name='Перенос с: '),
        ),
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='move_to',
            field=models.DateField(default='', null=True, verbose_name='перенос по: '),
        ),
    ]
