# Generated by Django 3.1.7 on 2022-04-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacShed', '0004_auto_20220419_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantionsheduleitem',
            name='child_year',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Год рож-я иждевенца: '),
        ),
        migrations.AlterField(
            model_name='vacantionsheduleitem',
            name='city',
            field=models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Проезд: '),
        ),
        migrations.AlterField(
            model_name='vacantionsheduleitem',
            name='days_count_move',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во дней после переноса '),
        ),
        migrations.AlterField(
            model_name='vacantionsheduleitem',
            name='move_from',
            field=models.DateField(blank=True, null=True, verbose_name='Перенос с: '),
        ),
        migrations.AlterField(
            model_name='vacantionsheduleitem',
            name='move_to',
            field=models.DateField(blank=True, null=True, verbose_name='перенос по: '),
        ),
    ]
