# Generated by Django 4.1.1 on 2022-12-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_cal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkCalendarRecord',
        ),
    ]
