# Generated by Django 4.1.1 on 2022-09-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TURV', '0029_merge_20220607_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantionShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='Период')),
                ('res_officer', models.CharField(default='', max_length=256, verbose_name='Ответственный')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'График отпусков',
                'verbose_name_plural': 'Графики отпусков',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='VacantionSheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur_from', models.DateField(verbose_name='Период с')),
                ('dur_to', models.DateField(verbose_name='Период по')),
                ('move_from', models.DateField(blank=True, null=True, verbose_name='Перенос с: ')),
                ('move_to', models.DateField(blank=True, null=True, verbose_name='перенос по: ')),
                ('child_year', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Год рож-я иждевенца: ')),
                ('city', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Проезд: ')),
                ('days_count', models.IntegerField(verbose_name='Количество дней')),
                ('days_count_move', models.IntegerField(blank=True, null=True, verbose_name='Кол-во дней после переноса ')),
                ('bound_shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vac_shed.vacantionshedule')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.employers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Элемент графика',
                'verbose_name_plural': 'Элементы графика',
                'ordering': ['-bound_shed__year'],
            },
        ),
    ]
