# Generated by Django 4.1.1 on 2022-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='sup_check',
            field=models.BooleanField(default=False, verbose_name='Утвержден СУП'),
        ),
        migrations.AlterField(
            model_name='vacantionsheduleitem',
            name='child_year',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Год рож-я иждивенца: '),
        ),
    ]
