# Generated by Django 4.1.1 on 2023-01-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0002_alter_vacantionsheduleitem_move_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='comm',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
    ]
