# Generated by Django 4.1.1 on 2022-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0002_vacantionsheduleitem_sup_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantionsheduleitem',
            name='sup_check',
        ),
        migrations.AddField(
            model_name='vacantionshedule',
            name='sup_check',
            field=models.BooleanField(default=False, verbose_name='Утвержден СУП'),
        ),
    ]
