# Generated by Django 4.1.1 on 2024-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0003_vacantionsheduleitem_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменен'),
        ),
    ]
