# Generated by Django 4.1.1 on 2022-09-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac_shed', '0003_remove_vacantionsheduleitem_sup_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantionsheduleitem',
            name='move_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основание переноса'),
        ),
    ]
