# Generated by Django 4.1.1 on 2022-12-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftshedmodel',
            name='del_check',
            field=models.BooleanField(default=0, verbose_name='Пометка удаления'),
        ),
    ]
