# Generated by Django 4.1.1 on 2022-12-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0014_alter_employers_aup'),
        ('shift_shed', '0002_shiftshedmodel_del_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftShedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=256, verbose_name='Месяц')),
                ('day_1', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 1')),
                ('day_2', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 2')),
                ('day_3', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 3')),
                ('day_4', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 4')),
                ('day_5', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 5')),
                ('day_6', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 6')),
                ('day_7', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 7')),
                ('day_8', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 8')),
                ('day_9', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 9')),
                ('day_10', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 10')),
                ('day_11', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 11')),
                ('day_12', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 12')),
                ('day_13', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 13')),
                ('day_14', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 14')),
                ('day_15', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 15')),
                ('day_16', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 16')),
                ('day_17', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 17')),
                ('day_18', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 18')),
                ('day_19', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 19')),
                ('day_20', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 20')),
                ('day_21', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 21')),
                ('day_22', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 22')),
                ('day_23', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 23')),
                ('day_24', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 24')),
                ('day_25', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 25')),
                ('day_26', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 26')),
                ('day_27', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 27')),
                ('day_28', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 28')),
                ('day_29', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 29')),
                ('day_30', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 30')),
                ('day_31', models.CharField(blank=True, max_length=4, null=True, verbose_name='День 31')),
                ('fact', models.FloatField(blank=True, help_text='Фактические часы', null=True, verbose_name='Факт. часов')),
                ('celeb', models.FloatField(blank=True, null=True, verbose_name='Праздничные')),
                ('bound_shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_shed.shiftshedmodel', verbose_name='Св. график')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.employers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник в графике',
                'verbose_name_plural': 'Сотрудники в графиках',
                'ordering': ['employer'],
            },
        ),
    ]
