# Generated by Django 4.1.1 on 2023-03-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0003_shiftsheditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsheditem',
            name='deviation',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Отклонение'),
        ),
    ]
