# Generated by Django 4.1.1 on 2023-03-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0004_shiftsheditem_deviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftsheditem',
            name='month',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='Месяц'),
        ),
    ]
