# Generated by Django 4.1.1 on 2023-03-20 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0005_alter_shiftsheditem_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftsheditem',
            name='bound_shed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shift_shed.shiftshedmodel', verbose_name='Св. график'),
        ),
    ]
