# Generated by Django 4.1.1 on 2023-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0006_alter_shiftsheditem_bound_shed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsheditem',
            name='norma',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Норма'),
        ),
    ]
