# Generated by Django 4.1.1 on 2023-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0016_tabel_half_month_check'),
        ('shift_shed', '0008_resemloyee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resemloyee',
            name='dep',
        ),
        migrations.AddField(
            model_name='resemloyee',
            name='dep',
            field=models.ManyToManyField(db_index=True, to='TURV.department', verbose_name='Подразделения'),
        ),
    ]
