# Generated by Django 4.1.1 on 2023-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0009_remove_resemloyee_dep_resemloyee_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftshedmodel',
            name='comment',
            field=models.CharField(max_length=200, null=True, verbose_name='Комментарий'),
        ),
    ]
