# Generated by Django 4.1.1 on 2023-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0010_shiftshedmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftshedmodel',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
    ]
