# Generated by Django 4.1.1 on 2024-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_shed', '0011_alter_shiftshedmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftshedmodel',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год: '),
        ),
    ]
