# Generated by Django 3.1.7 on 2022-04-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='vac_days',
            field=models.IntegerField(default=0, verbose_name='Максимально возможное кол-во дней'),
        ),
    ]
