# Generated by Django 4.1.1 on 2022-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='mainworkplace',
            field=models.BooleanField(blank=True, default=False, verbose_name='Основная специальность'),
        ),
    ]
