# Generated by Django 3.1.7 on 2021-04-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0001_auto_20210426_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelitem',
            name='sHours38',
        ),
    ]
