# Generated by Django 3.1.7 on 2022-04-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelitem',
            name='auto',
        ),
        migrations.DeleteModel(
            name='Automobile',
        ),
    ]
