# Generated by Django 3.1.2 on 2021-01-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0002_auto_20210122_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.department', verbose_name=''),
        ),
    ]
