# Generated by Django 3.1.7 on 2022-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0003_tabel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelitem',
            name='toxic_p',
            field=models.IntegerField(blank=True, default=0, verbose_name='Процент доплаты за вредность'),
        ),
    ]
