# Generated by Django 4.1.1 on 2022-10-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0003_alter_employers_mainworkplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_aup',
            field=models.BooleanField(default=False),
        ),
    ]
