# Generated by Django 3.1.2 on 2021-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0003_auto_20210125_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours1',
            field=models.IntegerField(help_text='Явки', verbose_name='Явки (Я)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours12',
            field=models.IntegerField(verbose_name='Сокращенная продолжительность для обучающихся без отрыва (УВ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours20',
            field=models.IntegerField(verbose_name='Время вынужденного прогула в случае признания увольнения незаконным (ПВ)'),
        ),
    ]
