# Generated by Django 3.1.2 on 2021-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0004_auto_20210127_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='hours1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы1'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours10',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы10'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours11',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы11'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours12',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы12'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours13',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы13'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours14',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы14'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours15',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы15'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours16',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы16'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours17',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы17'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours18',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы18'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours19',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы19'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы2'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours20',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы20'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours21',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы21'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours22',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы22'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours23',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы23'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours24',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы24'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours25',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы25'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours26',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы26'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours27',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы27'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours28',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы28'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours29',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы29'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы3'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours30',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы30'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours31',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы31'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы4'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы5'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours6',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы6'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours7',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы7'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours8',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы8'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours9',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Часы9'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours1',
            field=models.IntegerField(blank=True, help_text='Явки', null=True, verbose_name='Явки (Я)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дополнительный оплачиваемый отпуск (ОД)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Учебный отпуск (У)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сокращенная продолжительность для обучающихся без отрыва (УВ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Неоплачиваемый учебный отпуск (УД)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отпуск по беременности и родам (Р)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отпуск по уходу за ребенком до 3-х лет (ОЖ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отпуск без сохр. зп по разрешению работодателя (ДО)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Временная нетрудоспособность (Б)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Неоплачиваемый больничный (Т)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сокращенная продолжительность рабочего времени (ЛЧ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ночные (Н)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время вынужденного прогула в случае признания увольнения незаконным (ПВ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours21',
            field=models.IntegerField(blank=True, null=True, verbose_name='Невыходы на время исполнения гос. ил общ. обязанностей (Г)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours22',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогулы (ПР)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours23',
            field=models.IntegerField(blank=True, null=True, verbose_name='Работа в режиме неполного рабочего времени (НС)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выходные (В)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дополнительные выходные оплачиваемые (ОВ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours26',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дополнительные выходные неоплачиваемые (НВ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours27',
            field=models.IntegerField(blank=True, null=True, verbose_name='Забастовка (ЗБ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours28',
            field=models.IntegerField(blank=True, null=True, verbose_name='Неявки по невыясненным причинам (НН)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours29',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время простоя по вине работодателя (РП)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Работа в выходные и празд. (РВ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours30',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время простоя по причинам, не зависищим от работника и работодателя (НП)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours31',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время простоя по вине работника (ВП)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours32',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оплачиваемое отстранение от работы (НО)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours33',
            field=models.IntegerField(blank=True, null=True, verbose_name='Неоплачиваемое отстранение от работы (НБ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours34',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остановка работы про причине невыплаты ЗП (НЗ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сверхурочные (С)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вахтовый метод (ВМ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Служебная командировка (К)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Повыш. квалификации с отрывом от работы (ПК)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Повыш. квалификации с отрывом от рб. в другой мес-ти (ПМ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной оплачиваемый отпуск (ОТ)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time1',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени1'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time10',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени10'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time11',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени11'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time12',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени12'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time13',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени13'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time14',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени14'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time15',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени15'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time16',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени16'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time17',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени17'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time18',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени18'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time19',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени19'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени2'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time20',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени20'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time21',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени21'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time22',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени22'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time23',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени23'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time24',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени24'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time25',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени25'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time26',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени26'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time27',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени27'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time28',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени28'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time29',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени29'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time3',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени3'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time30',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени30'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time31',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени31'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени4'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time5',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени5'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time6',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени6'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time7',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени7'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time8',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени8'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='type_time9',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Вид времени9'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='v_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дней неявок'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='v_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Часов неявок'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='w_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Дней отработано'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='w_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Часов отработано'),
        ),
    ]
