# Generated by Django 4.1.1 on 2022-10-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0004_department_is_aup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='aup',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_aup', to='TURV.department', verbose_name='Отдел АУП'),
        ),
    ]
