# Generated by Django 3.1.7 on 2022-04-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0003_auto_20220421_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=256, verbose_name='Номер а\\м')),
                ('model', models.CharField(blank=True, max_length=256, null=True, verbose_name='Модель(необязательно) ')),
                ('unite_p', models.IntegerField(verbose_name='Процент доплаты')),
                ('used', models.BooleanField(default=1, verbose_name='Автомобиль используется')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['unite_p'],
            },
        ),
        migrations.AddField(
            model_name='tabelitem',
            name='auto',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.automobile', verbose_name='а/м'),
        ),
    ]
