# Generated by Django 3.1.2 on 2021-01-31 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0005_auto_20210201_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='positionOfPayment',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Ступень оплаты'),
        ),
    ]
