# Generated by Django 4.1.1 on 2022-11-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0006_department_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_filial',
            field=models.BooleanField(default=False),
        ),
    ]
