# Generated by Django 3.1.2 on 2021-02-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0006_auto_20210201_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='category',
            field=models.CharField(db_index=True, default='спец.', max_length=256, verbose_name='Категория стат. учета'),
        ),
        migrations.AddField(
            model_name='tabelitem',
            name='category',
            field=models.CharField(db_index=True, default='спец.', max_length=256, verbose_name='Категория стат. учета'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.department', verbose_name=' '),
        ),
    ]
