# Generated by Django 3.1.2 on 2021-02-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0007_auto_20210202_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='category',
        ),
        migrations.AlterField(
            model_name='employers',
            name='level',
            field=models.CharField(max_length=256, verbose_name='Разряд/категория'),
        ),
    ]
