# Generated by Django 4.1.1 on 2022-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0007_department_is_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Название дирекции')),
            ],
            options={
                'verbose_name': 'Дирекция',
                'verbose_name_plural': 'Дирекции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Название объединения')),
            ],
            options={
                'verbose_name': 'Объединение',
                'verbose_name_plural': 'Объединения',
                'ordering': ['name'],
            },
        ),
    ]
