# Generated by Django 3.1.7 on 2022-05-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0008_tabel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel',
            name='date',
        ),
    ]
