# Generated by Django 3.1.2 on 2021-02-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0008_auto_20210203_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='del_check',
            field=models.BooleanField(default=False, verbose_name='Пометка удаления'),
        ),
    ]
