# Generated by Django 4.1.1 on 2022-11-01 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0008_direction_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dir',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TURV.direction', verbose_name='Дирекция '),
        ),
        migrations.AddField(
            model_name='department',
            name='union',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TURV.union', verbose_name='Объединение '),
        ),
    ]
