# Generated by Django 4.1.1 on 2022-11-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0009_department_dir_department_union'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dir',
            new_name='dir_id',
        ),
    ]
