# Generated by Django 3.1.2 on 2021-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0009_tabel_del_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='del_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пометка удаления'),
        ),
    ]
