# Generated by Django 4.1.1 on 2022-11-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0010_rename_dir_department_dir_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='union',
            new_name='union_id',
        ),
    ]
