# Generated by Django 3.1.2 on 2021-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0010_auto_20210204_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='del_check',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пометка удаления'),
        ),
    ]
