# Generated by Django 4.1.1 on 2022-11-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0011_rename_union_department_union_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dir_id',
            new_name='dir',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='union_id',
            new_name='union',
        ),
    ]
