# Generated by Django 3.1.2 on 2021-02-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0011_auto_20210204_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelitem',
            name='category',
        ),
    ]
