# Generated by Django 4.1.1 on 2022-11-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0012_rename_dir_id_department_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dir',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.direction', verbose_name='Дирекция '),
        ),
        migrations.AlterField(
            model_name='department',
            name='union',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.union', verbose_name='Объединение '),
        ),
    ]
