# Generated by Django 3.1.2 on 2021-02-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0012_remove_tabelitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Разряд'),
        ),
    ]
