# Generated by Django 3.1.7 on 2022-05-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0013_auto_20220512_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='day',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Число'),
        ),
    ]
