# Generated by Django 4.1.1 on 2022-12-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0013_alter_department_dir_alter_department_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='aup',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_aup', to='TURV.department', verbose_name='Подчиненное подразделение'),
        ),
    ]
