# Generated by Django 3.1.7 on 2022-05-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0014_auto_20220512_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='comm',
            field=models.CharField(default='', max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='day',
            field=models.CharField(blank=True, db_index=True, default='0', max_length=256, null=True, verbose_name='Число'),
        ),
    ]
