# Generated by Django 3.1.2 on 2021-02-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0014_auto_20210211_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='shift_personnel',
            field=models.BooleanField(default=False, verbose_name='Сменный персонал'),
        ),
        migrations.AddField(
            model_name='employers',
            name='stand_worktime',
            field=models.FloatField(default=0, verbose_name='Норма часов'),
        ),
    ]
