# Generated by Django 4.1.1 on 2022-12-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0014_alter_employers_aup'),
        ('TURV', '0014_alter_employers_aup_alter_tabelitem_shours24_and_more'),
    ]

    operations = [
    ]
