# Generated by Django 4.1.1 on 2023-01-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0015_merge_20221227_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='half_month_check',
            field=models.BooleanField(blank=True, default=False, verbose_name='Половина месяца заполнена'),
        ),
    ]
