# Generated by Django 3.1.2 on 2021-02-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0015_auto_20210211_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours4',
            field=models.FloatField(blank=True, null=True, verbose_name='Сверхурочные (С)'),
        ),
    ]
