# Generated by Django 3.1.7 on 2022-05-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0015_auto_20220516_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel',
            name='comm',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Комментарий (НЕОБЯЗАТЕЛЬНО)'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='sHours2',
            field=models.FloatField(blank=True, null=True, verbose_name='Ночные (Н)'),
        ),
    ]
