# Generated by Django 3.1.2 on 2021-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0016_auto_20210211_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelitem',
            name='sHours35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Совмещение'),
        ),
    ]
