# Generated by Django 4.1.1 on 2024-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0017_alter_employers_stand_worktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', 'спец.'), ('9', 'рук.')], max_length=256, verbose_name='Разряд/категория'),
        ),
    ]
