# Generated by Django 3.1.7 on 2022-05-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0017_auto_20220516_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения: ')),
                ('active', models.BooleanField(default=True, verbose_name='Сообщение активно')),
                ('dfrom', models.DateField(blank=True, null=True, verbose_name='Дата начала показа: ')),
                ('dto', models.DateField(blank=True, null=True, verbose_name='Дата окончания показа: ')),
                ('always', models.BooleanField(blank=True, default=True, null=True, verbose_name='Показывать постоянно')),
                ('viewin', models.CharField(choices=[('1', 'Главное окно'), ('2', 'Окно табеля'), ('3', 'Окно редактирования табеля')], default='1', max_length=100)),
                ('mestype', models.CharField(choices=[('1', 'Обычное'), ('2', 'Особо важное'), ('3', 'О переносе отпуска')], default='1', max_length=100)),
                ('deps', models.ManyToManyField(blank=True, null=True, to='TURV.Department', verbose_name='Подразделения, для которых предназначена информация: ')),
                ('intypes', models.ManyToManyField(default=1, to='TURV.TabelType', verbose_name='Отображать в табелях: ')),
            ],
            options={
                'verbose_name': 'Сообщение пользователям',
                'verbose_name_plural': 'Система оповещения пользователей',
                'ordering': ['-id'],
            },
        ),
    ]
