# Generated by Django 3.1.2 on 2021-02-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0017_tabelitem_shours35'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='sup_check',
            field=models.BooleanField(blank=True, default=False, verbose_name='Проверен СУП'),
        ),
    ]
