# Generated by Django 3.1.7 on 2022-05-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0018_infomessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessages',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Особо важное'),
        ),
        migrations.AlterField(
            model_name='infomessages',
            name='intypes',
            field=models.ManyToManyField(default='1', to='TURV.TabelType', verbose_name='Отображать в табелях: '),
        ),
        migrations.AlterField(
            model_name='infomessages',
            name='mestype',
            field=models.CharField(choices=[('1', 'Обычное'), ('2', 'О переносе отпуска')], default='1', max_length=100),
        ),
    ]
