# Generated by Django 3.1.7 on 2022-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0019_auto_20220520_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessages',
            name='alldeps',
            field=models.BooleanField(default=True, verbose_name='Для всех'),
        ),
    ]
