# Generated by Django 3.1.2 on 2021-03-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0020_auto_20210309_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel',
            name='ro_check',
        ),
    ]
