# Generated by Django 3.1.7 on 2022-05-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0024_tabel_paper_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='corr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TURV.tabel', verbose_name='Корректировка к '),
        ),
    ]
