# Generated by Django 3.1.7 on 2022-05-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0025_tabel_corr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='iscorr',
            field=models.BooleanField(default=False),
        ),
    ]
