# Generated by Django 3.1.7 on 2022-06-02 20:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TURV', '0026_tabel_iscorr'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Виды сообщений от пользователей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('about', models.CharField(max_length=100, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('inwork', models.BooleanField(default=False, verbose_name='Принято в работу')),
                ('readed', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ на сообщение')),
                ('answer_readed', models.BooleanField(default=False, verbose_name='Ответ прочитан')),
                ('mes_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TURV.feedbacktypes', verbose_name='Вид сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение от пользователя',
                'verbose_name_plural': 'Сообщения пользователей',
                'ordering': ['-date'],
            },
        ),
    ]
