# Generated by Django 3.1.7 on 2022-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0027_auto_20220606_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='hours1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы1'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours10',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы10'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours11',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы11'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours12',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы12'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours13',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы13'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours14',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы14'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours15',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы15'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours16',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы16'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours17',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы17'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours18',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы18'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours19',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы19'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы2'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours20',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы20'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours21',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы21'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours22',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы22'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours23',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы23'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours24',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы24'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours25',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы25'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours26',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы26'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours27',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы27'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours28',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы28'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours29',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы29'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы3'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours30',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы30'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours31',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы31'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы4'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы5'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы6'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours7',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы7'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours8',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы8'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='hours9',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Часы9'),
        ),
    ]
