# Generated by Django 3.1.7 on 2022-06-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0027_feedback_feedbacktypes'),
        ('TURV', '0028_auto_20220606_1028'),
    ]

    operations = [
    ]
