# Generated by Django 4.1.1 on 2022-09-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0029_merge_20220607_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelitem',
            name='sHours39',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отсутствие по мобилизации'),
        ),
    ]
