# Generated by Django 4.1.1 on 2022-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0030_tabelitem_shours39'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='onescode',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Код подразделения в 1С '),
        ),
    ]
