# Generated by Django 3.1.2 on 2021-03-21 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TURV', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='tabelitem',
            name='sHours37',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пенсионный'),
        ),
       
    ]
