# Generated by Django 3.1.2 on 2021-03-23 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TURV', 'add_oz'),
    ]

    operations = [

        migrations.AlterField(
            model_name='employers',
            name='positionOfPayment',
            field=models.CharField(max_length=3, verbose_name='Ступень оплаты'),
        )
    ]
